apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: annotator-frontend
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.frontend.ingress.host }}`) && PathPrefix(`{{ .Values.frontend.ingress.pathPrefix }}`)
    kind: Rule
    middlewares:
      - name: test-compress
        namespace: {{.Release.Namespace}}
    services:
    - name: annotator-frontend
      port: {{ .Values.frontend.service.port }}
