# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and push release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  docker-build-and-push:
    name: Build and push Docker images
    uses: ./.github/workflows/reusable-docker-build.yaml

    permissions:
      contents: read
      packages: write
      pull-requests: write

    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

    with:
      dockerhub-enable: true
      ghcr-enable: true
      platforms: linux/amd64,linux/arm64
      file: Dockerfile.release

      image-names: |
        kamikazer/${{ github.event.repository.name }}
        ghcr.io/${{ github.repository }}
